version: "3"

services:
  frontend-staging:
    container_name: frontend-staging
    image: sorada1111/eshop:front1-staging
    environment:
      CLIENT_URL: http://backend-staging:3200
    ports:
      - "6100:4100"

  # frontend-shop-staging:
  #   container_name: frontend-shop-staging
  #   image: sorada1111/eshop:front2-staging
  #   environment:
  #     CLIENT_URL: http://backend-staging:3200
  #   ports:
  #     - "6200:4200"






      