version: "3"

services:
  frontend-dev:
    container_name: frontend-dev
    image: sorada1111/eshop:front1-dev
    environment:
      CLIENT_URL: http://backend-dev:3000
    ports:
      - "4100:4100"

  frontend-shop-dev:
    container_name: frontend-shop-dev
    image: sorada1111/eshop:front2-dev
    environment:
      CLIENT_URL: http://backend-dev:3000
    ports:
      - "4200:4200"